language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/0.19.0/
    - sysconfcpus

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install -g elm@0.19.0 elm-test@elm0.19.0 elm-format@elm0.19.0
  - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-old "$@"' > $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm

script:
  # - elm-format --validate src tests examples
  - elm-test
